# Generated by Django 3.0.4 on 2020-09-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20200919_1309'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistReviews',
            new_name='ArtistReview',
        ),
    ]
