# Generated by Django 3.0.3 on 2020-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200307_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('artist', 'Client'), ('client', 'Artist')], default='artist', max_length=10),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
