# Generated by Django 3.0.3 on 2020-03-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200307_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
