# Generated by Django 3.0.4 on 2020-04-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200419_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avater/default.jpg', null=True, upload_to='avatar/%Y-%M-%D/'),
        ),
    ]
