# Generated by Django 3.0.3 on 2020-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20200919_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, help_text='Short Bio', max_length=255, null=True),
        ),
    ]
