# Generated by Django 3.0.3 on 2020-09-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0023_auto_20200919_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_follower', to='register.User')),
                ('user_following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_following', to='register.User')),
            ],
        ),
    ]
