# Generated by Django 3.0.4 on 2020-06-14 12:19

import artistArt.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0019_user_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.CharField(max_length=500)),
                ('post_status', models.CharField(choices=[('public', 'Public'), ('draft', 'Draft'), ('private', 'Private')], default='private', max_length=20)),
                ('image', models.ImageField(default='art_image/default.jpg', upload_to=artistArt.models.art_directory_stor_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistArt.ArtCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
    ]
