# Generated by Django 3.0.4 on 2020-06-16 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artistArt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
