# Generated by Django 3.0.4 on 2020-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistArt', '0004_auto_20200617_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistart',
            name='tags',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='artistart',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
